### ISSUE TITLE
Add some more values / explanations

### ISSUE THREAD

**Issue by capstan1** [chipriley/lovelace-css-values#1]
paper-slider-height:   (in px), height of the slider (gives you the ability of having this type of sliders) ![image](https://user-images.githubusercontent.com/17147867/54877975-13d59900-4e26-11e9-81b1-72fd4c256cba.png)

 paper-slider-container-color:  color of the part of the slider which is not active
paper-slider-active-color: color of the part of the slider which is active, can even be a gradient, like paper-slider-active-color: 'linear-gradient(to right, transparent , #f4c242 90%)'

**Comment by chipriley** [comment]
Updated in `3d86036`.
